### ISSUE TITLE
Expected type utf8 for Argument 'location'  but got type 'undefined'

### ISSUE THREAD

**Issue by udoprog** [benzea/gnome-shell-extension-redshift#1]
Encountered the following problem when trying to install the extension:

```
Expected type utf8 for Argument 'location'  but got type 'undefined'
```

I traced down the problem to:
https://github.com/benzea/gnome-shell-extension-redshift/blob/master/redshift%40benjamin.sipsolutions.net/lib.js#L67

I'm not sure why it extension.metadata.locale is `undefined`. I've also installed your extension in my `~/.local` so I don't know why it's being triggered at all.

I patched away the if statement for now, and I'm only using the `localeDir` code, and now it works.

I'm on Debian Sid, and I'm using `gnome-shell` 3.22.2, and I've patched `gnome-settings-daemon` 3.22.

**Comment by benzea** [comment]
Alright, this will work as a workaround. Simply creating the "locale" directory before running make-zip.sh would have also done the job. I just happened to have it here and git doesn't keep empty folders obviously.
