### ISSUE TITLE
Temperature setting works only in time based

### ISSUE THREAD

**Issue by olegTarassov** [benzea/gnome-shell-extension-redshift#10]
Setting to geolocation or last known location does not seem to work.

Tested in the day in either case and the application uses the nighttime temperature.

System: Fedora 25 wayland
config:
daytime: 6500k
nighttime: 4800k
length: 10
source of sunset/sunrise: last known
time in sunrise: 7:30
time in sunset: 18:30

**Comment by benzea** [comment]
Last known only works if you use the "geoclue" for a while and it got a location once.

Right now this is the intended behaviour. It might make sense to grey out the option/warn if there is no cached location yet.

**Comment by olegTarassov** [comment]
Maybe I was not clear; I did enable geo location and while it is enabled the temperature is set to nighttime even though it is clear day ( 10:43 am ).

After the location has been set, I tried using last known thinking static would do better job, which it had not.

Maybe I am missing something?

Only thing that works is time based option which I have statically set.

**Comment by benzea** [comment]
Sounds like geoclue is simply not finding the correct location for you. You can check with gnome-maps where it places you
