### ISSUE TITLE
Doesn't seem to be following time-based settings

### ISSUE THREAD

**Issue by scoronado12** [benzea/gnome-shell-extension-redshift#13]
Using Antergos, I have installed this package from the AUR since switching from the X11 implementation of redshift to Wayland. On X11, depending on the time of day, the screen filter gets more intense. This does not seem to be the case on Wayland. I would have to advance the slider myself when it is dark outside.

**Comment by benzea** [comment]
Probably it didn't get a location from geoclue. Have you tried setting a fixed time for sunset/sunrise?
