### ISSUE TITLE
Doesn't dim my workstation monitor

### ISSUE THREAD

**Issue by mjsaltzman** [benzea/gnome-shell-extension-redshift#16]
My (somewhat old) home workstation has an nVidia C77 GeForce 8300 onboard video controller, using VGA output. It runs Fedora 25 with Wayland, all up to date. FWIW, the monitor is a HP Pavilion 27xw. The workstation display doesn't dim at all in response to GNOME Redshift controls. My laptop (also nVidia controller in a Dell Latitude 3420) does fine with its internal display and with the HP monitor as its external display. Earlier versions of Redshift-gtx on Fedora 24 worked fine on both machines. Is there something I need to do here, or have I encountered a bug?

**Comment by benzea** [comment]
I think this is a duplicate of #8 (with a somewhat better description). Closing this one, but as a note: This extension goes through gnome-settings-daemon and uses the colour profile code. The issue you are seeing sounds like there is a bug somewhere in the colour management subsystem. I would assume that you also cannot successfully apply a (full screen) colour profile to that monitor.
