### ISSUE TITLE
Redshift package of gnome-settings-daemon is out of date

### ISSUE THREAD

**Issue by mjsaltzman** [benzea/gnome-shell-extension-redshift#21]
Fedora recently released an update of gnome-settings-daemon to 3.22.2-1.fc25, but the version supplied in the redshift repository is gnome-settings-daemon-3.22.1-3.redshift.fc25.

**Comment by benzea** [comment]
This has nothing to do with this code.

Also, on rawhide you already get the new upstream support for "night light" which renders this package obsolete.
