### ISSUE TITLE
Latitude and longitude are swapped

### ISSUE THREAD

**Issue by Susensio** [benzea/gnome-shell-extension-redshift#25]
When I set up for example Latitude=50 Longitude=0, the process launched is `redshift -l 0 50` and according to redshift documentation it should be Latitude FIRST. 
This results in wrong behavior.
Setting those values swapped in the settings menu seems to solve the issue.

**Comment by benzea** [comment]
Sorry, you found the redshift extension … this one doesn't actually call redshift.

**Comment by Susensio** [comment]
Isn't this the https://extensions.gnome.org/ extension for redshift?

**Comment by benzea** [comment]
Nope, I didn't realise it existed when naming this one …
