### ISSUE TITLE
Cannot find the extension

### ISSUE THREAD

**Issue by EgidioCaprino** [benzea/gnome-shell-extension-redshift#7]
Hi @benzea,

I have installed the [AUR package](https://aur.archlinux.org/packages/gnome-shell-extension-redshift-native-git/) but I cannot find the extension.

[Screenshot](https://postimg.org/image/fotmkxiyb/)

**Comment by adriaanzon** [comment]
Have you tried to log out and back in?

**Comment by benzea** [comment]
Just switch to "installed extensions".
